config/routes.rb
Rails.application.routes.draw do

  root 'posts#index'

  resources :posts
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
end

app/models/post.rb
class Post < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_action :find_post, only: [:show, :edit, :update, :destroy]

  def index
    @posts = Post.all
  end

  def show
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)

    if @post.save
      redirect_to @post, notice: "The post was created!"
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @post.update(post_params)
      redirect_to @post, notice: "Update successful!"
    else
      render 'edit'
    end
  end

  def destroy
    @post.destroy
    redirect_to root_path, notice: "Post deleted!"
  end

private

  def post_params
    params.require(:post).permit(:title, :content, :category_id)
  end

  def find_post
    @post = Post.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Marmelade</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
    <%= render 'layouts/shared/nav' %>
  </body>
</html>

app/views/layouts/shared/_error_messages.html.erb
<% if @post.errors.any? %>
  <div>
    <p><%= pluralize(@post.errors.count, "error") %> prevented it from being saved.</p>
    <ul>
      <% @post.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/shared/_nav.html.erb
<% Category.all.each do |category| %>
  <li>
    <%= link_to category.name, posts_path(category: category.name) %>
  </li>
<% end %>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>

  <%= render 'shared/error_messages' %>

  <%= f.collection_select(:category_id, Category.all, :id, :name, {prompt: "Choose a category" }) %><br>
  <%= f.label :title %><br>
  <%= f.text_field :title, placeholder: "Type the post title here" %><br>
  <%= f.label :content %><br>
  <%= f.text_area :content, size: "60x12", placeholder: "Type the post text here" %><br>

  <%= f.submit %>

<% end %>

app/views/posts/edit.html.erb
<h1>Edit Post</h1>
<%= render 'form' %>
<%= link_to "Back", root_path %>

app/views/posts/index.html.erb
<% @posts.each do |post| %>
  <h1><%= link_to "post.title", post %></h1>
  <p><%= post.content %></p>
<% end %>

app/views/posts/new.html.erb
<h1>New Post</h1>
<%= render 'form' %>
<%= link_to "Back", root_path %>

app/views/posts/show.html.erb
<h1><%= @post.title %></h1>
<p><%= @post.content %></p>
<%= link_to "Edit", edit_post_path(@post) %>
<%= link_to "Delete", @post, method: :delete, data: { confirm: "Are you sure?" %>